@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Lucas Basso",
  "email": "lucas@basso.com",
  "password": "1234567"
}

###

# @name authenticate
POST {{baseUrl}}/sessions   
Content-Type: application/json
X-correlation-id: 'oiajdoiawjdiajd

{
  "email": "lucas@basso.com",
  "password": "12345678"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta",
  "content": "Conteúdo teste"
}

###

# @name get_question_by_slug
GET {{baseUrl}}/questions/nova-pergunta
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta",
  "content": "Conteúdo teste"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
